name: Install Qt (universal)

jobs:
  install-qt:
    - name: Install host Qt (Windows MSVC arm64)
      if: runner.os == 'Windows' && matrix.architecture == 'arm64'
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: "==3.1.*"
        py7zrversion: ">=0.20.2"
        version: ${{ matrix.qt_version }}
        host: "windows"
        target: "desktop"
        arch: ${{ matrix.qt_arch }}
        modules: ${{ matrix.qt_modules }}
        cache: ${{ inputs.is_qt_cached }}
        cache-key-prefix: host-qt-arm64-windows
        dir: ${{ github.workspace }}\HostQt
        set-env: false

    - name: Install Qt (macOS, Linux & Windows MSVC)
      if: matrix.msystem == ''
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: "==3.1.*"
        py7zrversion: ">=0.20.2"
        version: ${{ matrix.qt_version }}
        target: "desktop"
        arch: ${{ matrix.qt_arch }}
        modules: ${{ matrix.qt_modules }}
        tools: ${{ matrix.qt_tools }}
        cache: ${{ inputs.is_qt_cached }}
