name: Build

on:
  workflow_call:
    inputs:
      build_type:
        description: Type of build (Debug, Release, RelWithDebInfo, MinSizeRel)
        type: string
        default: Debug
      is_qt_cached:
        description: Enable Qt caching or not
        type: boolean
        default: true

jobs:
  windows:
    uses: ./.github/workflows/by-os/windows.yml
    with:
      is_qt_cached: ${{inputs.is_qt_cached}}
      build_type: ${{inputs.build_type}}
  linux:
    uses: ./.github/workflows/by-os/linux.yml
    with:
      is_qt_cached: ${{inputs.is_qt_cached}}
      build_type: ${{inputs.build_type}}
  macos:
    uses: ./.github/workflows/by-os/macos.yml
    with:
      is_qt_cached: ${{inputs.is_qt_cached}}
      build_type: ${{inputs.build_type}}
