name: Commit verification

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate Commits with Commitlint
        uses: joberstein/actions-commitlint-validation@v1-dist
